package pxf.weixin.dao;

import pxf.weixin.model.AccessToken;

public interface AccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int insert(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int insertSelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    AccessToken selectByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccessToken record);
}