package pxf.weixin.dao;

import org.apache.ibatis.annotations.Param;
import pxf.weixin.result.MessageReplyConfig;

import java.util.List;

public interface MessageReplyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply_config
     *
     * @mbggenerated
     */
    int insert(MessageReplyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply_config
     *
     * @mbggenerated
     */
    int insertSelective(MessageReplyConfig record);

    List<String> selectAllKeyWords();

    String selectResponseMsg(String keyWord);
}